name: Real Estate Craft
main: com.rurd4me.realestatecraft.RealEstateCraft
version : .1
softdepend: [WorldGuard, WorldEdit]
commands:
  realtor:
    description : Minecraft Realty Office Commands
    usage: /<command> <region_id> <amount>